name: React App Build and Run with Linting

on:
  push:
    branches:
      - main # Change this to your main branch

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # You can change this to your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Lint React App
        run: npm run lint

      - name: Build React App
        run: npm run build

      - name: Start React App
        run: npm start
